### ISSUE TITLE
Cannot be used with multiprocess programs

### ISSUE THREAD

**Issue by ghost-cai** [TESTARtool/TESTAR_dev#371]
Cannot be used with multiprocess programs. Such as WPS Office which from China.
Useing window_title ,the widget could not be detected. No green point.

**Comment by ferpasri** [comment]
Thanks @ghost-cai ,
I'm going to add more information about this issue to be tracked by our team.

**System Under Test**
WPS Office: https://www.wps.com/

**SUT Connection Issues due to multiprocess**

- Using COMMAND_LINE with the default launcher `"C:\Users\testar\AppData\Local\Kingsoft\WPS Office\ksolaunch.exe"` does not work because the SUT later executes another process named `wpx.exe`. As mentioned, this is due to multiprocess limitations.

![image](https://github.com/TESTARtool/TESTAR_dev/assets/32359126/2a0334ef-b259-4c2c-afda-596cfb04187c)

- Using COMMAND_LINE with the executable `"C:\Users\testar\AppData\Local\Kingsoft\WPS Office\12.2.0.13215\office6\wps.exe"` launches the SUT and allows TESTAR to connect.

![image](https://github.com/TESTARtool/TESTAR_dev/assets/32359126/c4369d29-abdc-485f-943f-4ac95c714de2)

**Widget recognition issue due to Qt system**

- The default `desktop_generic` protocol with the adequate COMMAND_LINE allows TESTAR to recognize the widgets but are recognized as `Blocked` by our UIAutomation. For this reason, these are not displayed as clickable (green dot).

![image](https://github.com/TESTARtool/TESTAR_dev/assets/32359126/ad0e19fd-cbf3-4274-83e5-3e57ff03f126)

- This seems to be related to the fact that WPS Office is a Qt application.
- We need to work on #299, which contains, in addition to the visual feature, a fix for Qt applications.

![image](https://github.com/TESTARtool/TESTAR_dev/assets/32359126/f12d711a-bab5-4978-9982-57aa0b85cdcf)

**Comment by ferpasri** [comment]
Working on a solution: [master_desktop_Qt](https://github.com/TESTARtool/TESTAR_dev/tree/master_desktop_Qt)

**Comment by ferpasri** [comment]
Thanks for the report,

With the update #388

1. TESTAR has been updated to derive actions in Qt applications  

https://github.com/TESTARtool/TESTAR_dev/wiki/TESTAR-for-Qt-applications

2. The `SUTProcesses` setting has been refactored to allow the connection with multi-processes SUTs 

The TESTAR user can indicate with regular expressions which processes conform to the SUT ( `.*wps.exe.*` )

https://github.com/TESTARtool/TESTAR_dev/wiki/3-TESTAR-configuration-and-settings#connect-with-a-multi-processes-sut-advanced-dialog

<img width="462" alt="multiprocess" src="https://github.com/TESTARtool/TESTAR_dev/assets/32359126/5c97f46d-d6e8-474a-911c-189be1622f07">
